### ISSUE TITLE
Add toggle for OTB / K&R braces

### ISSUE THREAD

**Issue by Nick-Lucas** [Testura/Testura.Code#1]
Different organisations will have a different set of style guidelines for braces.

It would be great if we had a setting to switch between OneTrueBrace and K&R, when generating files.

It's probably possible to work around this right now with a post processing .Replace or Regex

**Comment by MilleBo** [comment]
Yeah, I also wonder if you can simply replace/remove the OpenBraceToken/ClosebraceToken? I haven't done a lot post editing. But I will look into it. 

In general it feels like it would be good to have some kind of global configuration file (or class) where you can edit style settings.

**Comment by MilleBo** [comment]
It was actually a lot easier than I thought. If statements have overload for both block and statements so I'm just creating a new method which take an expression staement instead of a block. 

So for example: 

`conditional.If(new ValueArgument(2), new ValueArgument(3), ConditionalStatements.Equal, Statement.Expression.Invoke("MyMethod").AsStatement())`

Will turn into:

```c#
 if (2 == 3)
    MyMethod();
```

I guess that's how you want it?

**Comment by Nick-Lucas** [comment]
I'm not sure, we might be thinking along different lines. OTB/K&R are kind of terse terms, easier to see:

OneTrueBrace style:
```
Public SomeClass 
{
  void SomeMethod()
  {
    ...
  }
}
```

K&R:
```
Public SomeClass {
  void SomeMethod() {
    ...
  }
}
```

**Comment by MilleBo** [comment]
Oh I'm not sure why I tought about the other thing. But I guess it's good to have. 

But I have a solution to your problem now, you just have to send in an argument to the CodeSaver class.

Example: 

```c#
var codeSaver = new CodeSaver(new List<OptionKeyValue> {  new OptionKeyValue(CSharpFormattingOptions.NewLinesForBracesInMethods, false) });
var code = codeSaver.SaveCodeAsString(
	new ClassBuilder("TestClass", "test")
		.WithMethods(
			new MethodBuilder("MyMethod")
			.Build())
		.Build());
```

Which will give you: 

```c#
namespace test
{
    public class TestClass
    {
        void MyMethod() {
        }
    }
}
```
CSharpFormattingOptions contains a lot of useful stuff for formatting the code.

**Comment by MilleBo** [comment]
The solution is now inside the 0.2.0 release, will also adda short about it inside the wiki.
