### ISSUE TITLE
Add API Documentation 

### ISSUE THREAD

**Issue by Nick-Lucas** [Testura/Testura.Code#2]
It would be really great if there were both documentation comments throughout the API, and a website generated from them. The readme is good enough to get started, but I'm also a fairly experienced developer and know to look at the unit tests for examples.

Once you've got documentation comments, it's really easy to build a GitHub website using [DocFX](https://dotnet.github.io/docfx/)

For instance I built this recently https://nick-lucas.github.io/EntryPoint/

**Comment by MilleBo** [comment]
Sounds like a good idea. I made a couple of examples and listed the most-used method/classes in the wiki but it would be good to have full documentation page. 

So I will look at yours later tonight and see if I can make something similar.

**Comment by MilleBo** [comment]
We now have a page with the API: 

https://testura.github.io/Code/api/index.html

Also added a link to it inside the readme and on the wiki.
