### ISSUE TITLE
Typo in the repository description ("saving and and compiling")

### ISSUE THREAD

**Issue by ironcev** [Testura/Testura.Code#29]
There is a typo in the project description. The word "and" comes twice in the sentence: "saving and **and** compiling C# code"

**Comment by MilleBo** [comment]
Oh, thanks for pointing it out and fixed it now.

**Comment by ironcev** [comment]
Hi Mille,
thank you for fixing it so quickly :-)
BDW I find Testura.Code to be very useful and simple to use. That's why I've added it to the curated list of awesome Roslyn projects that I've just created. Here, in case you want to take a look: https://github.com/ironcev/awesome-roslyn

**Comment by MilleBo** [comment]
That's a really cool list and thanks for adding me. I will for sure looking at the other projects too :-)
