### ISSUE TITLE
Bug: generation of nullable types

### ISSUE THREAD

**Issue by Sigvaard** [Testura/Testura.Code#32]
Nullable types generate correctly only for primitives, for other types it generates it wrongly:

```csharp
public Nullable`1Property { get; set; }
```

```csharp
classProperties.Add(new AutoProperty(propertyName, typeof(DateTime?), PropertyTypes.GetAndSet, modifiers, propertyAttributes));`
```

**Comment by MilleBo** [comment]
Thanks for reporting. I will look into it.

**Comment by MilleBo** [comment]
Hey,

The bug is fixed and I released a new 0.9.0 release.

**Comment by Sigvaard** [comment]
That's cool it works fine now. Isn't there any way to make it universal ? Other than checking each time like

https://github.com/Testura/Testura.Code/commit/0bed2b21746932326b03f10fda7c6a67bc2311df#diff-24486341b30753e4810405e00dc12b3cR132

**Comment by MilleBo** [comment]
oh, that's just bad. I have totally missed short. And I even have ushort :/ 

https://github.com/Testura/Testura.Code/blob/master/src/Testura.Code.Tests/Generators/Common/TypeGeneratorTests.cs

Nullable is a bit of a special case so I tried to do it just for "Predefined types" as you usually don't use it for anything else. But maybe I have to check for a better and more universal solution as you say.
