### ISSUE TITLE
Interface creation similar to Classes

### ISSUE THREAD

**Issue by francisminu** [Testura/Testura.Code#36]
Hi,

Would it be possible to get Interfaces created, just like how we have classes?

Thanks,
Minu Francis

**Comment by MilleBo** [comment]
Hey! 

Sounds like a good idea. I will try to work on something.

**Comment by MilleBo** [comment]
I have now updated with a new 0.11.0 release: 

- Added interface builder
- Changed method builder so it add a semicolon if you set body to null

So the new class is called `InterfaceBuilder` and works the same as `ClassBuilder` except that it miss fields/constructor. I also changed the MethodBuilder so when you call it like this:

`var builder = new MethodBuilder("MyMethod").WithBody(null).Build()`

It will create this: 

`void MyMethod();`

So you should be able to create good interfaces now.
