### ISSUE TITLE
EnumBuilder

### ISSUE THREAD

**Issue by Illeris** [Testura/Testura.Code#46]
Can Enum types be generated? Quid an "EnumBuilder" ?

**Comment by MilleBo** [comment]
We didn't have that but it was easy to fix so I have created a PR that you can look at. It contains a couple of examples on how you can create them too. 

The only thing it doesn't support right now are attributes on individual member values. Is that something you need?

**Comment by Illeris** [comment]
Thx for the fast response. Don't think attributes on members will be needed, if members can be mapped to integer values it should cover all cases. I'm on it, keep you posted. Like what you guys have done so far. Had a class with dozen of helper methods, but this project is cleaner :)

**Comment by Illeris** [comment]
Works like a charm, nice !!
