### ISSUE TITLE
Bug in rendering Guid? property types

### ISSUE THREAD

**Issue by Illeris** [Testura/Testura.Code#49]
Think PropertyGenerator::Create contains a bug for a property of Guid? type. It is rendered like this in code file: Nullable'1<propertyname>

For primitive datatypes it goes perfectly well...

**Comment by Illeris** [comment]
Adding this:

if (type == typeof(Guid))
            {
                typeSyntax = IdentifierName("Guid");
            }

to TypeGenerator::CheckPredefinedTypes, after all the other checks, appears to solve the issue

**Comment by MilleBo** [comment]
Nice find, can you create a PR with the fix + a test in `TypeGeneratorTests.cs`? If not I can do it later today.

**Comment by MilleBo** [comment]
I found some time to check on it and it seems like we don't support structs that well (or well nullable structs). So I added support for that but made some specific tests for GUID as it's a pretty normal struct to use.
