### ISSUE TITLE
Ability to generate constructor chaining

### ISSUE THREAD

**Issue by Nitin5acc** [Testura/Testura.Code#55]
Hello,

How can we have constructor chaining? something like - 
```
public ValidLocationRule(PlateFact plateLocationFact) : base(plateLocationFact)
        {
            _plateLocationFact = plateLocationFact;
        }
```

**Comment by MilleBo** [comment]
Hey! We don't support that right now but I can add it later today and upload a new version.

**Comment by MilleBo** [comment]
I have added this in the new version, you simply add a `ConstructorInitializer` object when creating your constructor. Like this: 

`ConstructorGenerator.Create("MyClass", BodyGenerator.Create(), constructorInitializer: new ConstructorInitializer(ConstructorInitializerTypes.Base, new List<Argument> { new ValueArgument("myText")})))`

Which will give you:

`"MyClass():base("myText"){}"`
