### ISSUE TITLE
using statements with the namespace 

### ISSUE THREAD

**Issue by Nitin5acc** [Testura/Testura.Code#56]
Hi,

is there an ability to generate using statements with the namespace ?

**Comment by MilleBo** [comment]
You want them within the namespace? Like: 

```
namespace myNamespace
{
   using System; 
}
```

Because currently we only support usings at the the top of the file: 

```
using System; 

namespace myNamespace
{
}
```

But guess I can make it as a flag if you want it at the top. If I understand you correctly?

**Comment by Nitin5acc** [comment]
Thanks in advance. 

Yes, Above is what we need exactly.

**Comment by Nitin5acc** [comment]
hello ,

just checking if this is available in new version.

**Comment by MilleBo** [comment]
Sorry totally missed to update the issues. I started to work on it but I didn't like the solution so I decided to create 0.15.0 without it. I will try to look at this week (a bit busy now) and see if I can figure out a better solution.

**Comment by MilleBo** [comment]
It's been a really long time since this issue was created and I think many perfer the new file scoped type (which we have added support for). I'm open to look at it again if someone still request it.
