### ISSUE TITLE
Feature Request- ability to generate method  parameters documentation along with summary  

### ISSUE THREAD

**Issue by Nitin5acc** [Testura/Testura.Code#57]
Hello,
Is it possible to have an ability to generate method parameters  documentation as xml comment? 
like we generate a method summary. 

  `.AddSummary(string comments)`

**Comment by MilleBo** [comment]
This is now possible with 0.15.0 when you create a new parameter in the method builder: 

`new Parameter("MyParameter", typeof(string), xmlDocumentation: "Some documentation")`
