### ISSUE TITLE
Need to add InterfaceBuildMember

### ISSUE THREAD

**Issue by dgauerke** [Testura/Testura.Code#63]
I was in need of creating a namespace with multiple interfaces and classes.  The class builder was supported, but not the interface.  Here is the code I added

    public class InterfaceBuildMember : IBuildMember
    {
        private readonly TypeDeclarationSyntax _interface;

        public InterfaceBuildMember(InterfaceBuilder interfaceBuilder)
        {
            _interface = interfaceBuilder.BuildWithoutNamespace();
        }

        public InterfaceBuildMember(TypeDeclarationSyntax @interface)
        {
            _interface = @interface;
        }

        public SyntaxList<MemberDeclarationSyntax> AddMember(SyntaxList<MemberDeclarationSyntax> members)
        {
            return members.Add(_interface);
        }
    }

**Comment by MilleBo** [comment]
Oh I must have missed that! Could you create a pull request with this code (and maybe a unit test?) so we can add it to the next release?

**Comment by dgauerke** [comment]
I haven’t done that before, but I’ll give it a shot.

**Comment by MilleBo** [comment]
This have now been added to the code base and will be included in next nuget update.
