### ISSUE TITLE
ThatInheritFrom - fails on multiple types

### ISSUE THREAD

**Issue by dszryan** [Testura/Testura.Code#64]
i think the fix would be

file: src/Testura.Code/Builders/Base/TypeBuilderBase.cs 
line: 183
```
                syntaxNodeOrToken[n] = SyntaxFactory.SimpleBaseType(TypeGenerator.Create(_inheritance[n / 2]));
                if (n + 1 < (_inheritance.Count * 2) - 1)
```

**Comment by MilleBo** [comment]
Oh thanks I will check it out and make a fix.

**Comment by dszryan** [comment]
LINQ approach - should give the same result

        protected BaseListSyntax CreateBaseList() =>
            _inheritance.Any()
                ? SyntaxFactory.BaseList(
                    SyntaxFactory.SeparatedList<BaseTypeSyntax>(
                        _inheritance.ToList().Select(i => SyntaxFactory.SimpleBaseType(TypeGenerator.Create(i))),
                        Enumerable.Range(0, _inheritance.Count - 1).Select(_ => SyntaxFactory.Token(SyntaxKind.CommaToken))))
                : null!;

**Comment by MilleBo** [comment]
Cool I had totally missed the built in seperator list. Thanks! It should now be fixed in the 0.17.0  version,

**Comment by dszryan** [comment]
slight issue. there is an extra comma at the end

**Comment by MilleBo** [comment]
Oh damn, I did a unit test but used "contains" to assert the string and forgot to manually check so totally missed the extra comma. I will fix it later today.

**Comment by MilleBo** [comment]
This is now fixed and will come in next release.
