### ISSUE TITLE
support for OperatorDeclarationSyntax

### ISSUE THREAD

**Issue by dszryan** [Testura/Testura.Code#65]
is it possible to generate `static bool operator ==` operations in a class?

**Comment by MilleBo** [comment]
Hey, 

Sadly I haven't implemented override of operators yet. But I can look at it if it's something that you need?

**Comment by dszryan** [comment]
yes, please. need it for completeness for IEquatable implementation

**Comment by MilleBo** [comment]
I have uploaded a new version (0.17.0) that hopefully have what you are looking for. You simply specify it when creating the method. For example:

```
var method = new MethodBuilder("MyMethod")
                .WithModifiers(Modifiers.Public, Modifiers.Static)
                .WithOperatorOverloading(Operators.Equal)
                .WithBody(BodyGenerator.Create())
               .Build();
``` 

It should give you:

``` 
public static MyMethod operator ==() { }
```

**Comment by dszryan** [comment]
thank you :)

**Comment by dszryan** [comment]
worked perfectly.
