### ISSUE TITLE
[Request] Can you please make the Wiki public so that changes can be made to the Wiki?  

### ISSUE THREAD

**Issue by jeffward01** [Testura/Testura.Code#69]
Hello!

I am trying to fix some spelling errors and add some examples to the Wiki.  First I wanted to fix the spelling errors of "Declaration".

I tried to create a new branch and got this message when I was committing.  I assume its because the wiki is private and not open to public edits.

## Errors I encountered

**New Branch I created locally when I cloned the Wiki**
![image](https://user-images.githubusercontent.com/12589359/133851626-05b809f3-8f91-47f1-a0de-1286b091177f.png)

**Error Message**
![image](https://user-images.githubusercontent.com/12589359/133851545-2b5ddf51-61ac-4352-9926-8d27ba8acd17.png)

## My Request
Please make the Wiki 'public' and open to public contributions 

Thanks for the AWESOME library!!

**Comment by MilleBo** [comment]
Hey there, sorry for the late answer but I have fixed so the wiki is open for everyone now. Thanks for your interest in the project!
